server:
  port: ${SERVER_NEWS_SERVICE_PORT:8081}

spring:
  application:
    name: tech-news-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NEWS_NAME:tech-news-db}
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NEWS_NAME:tech-news-db}
    user: ${DB_USER:auth_user}
    password: ${DB_USER:auth_user}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS1:localhost:9092}, ${KAFKA_BOOTSTRAP_SERVERS2:localhost:9093}, ${KAFKA_BOOTSTRAP_SERVERS4:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# Feign Client Dev.to
devto:
  api:
    url: https://dev.to/api
    keys: ${DEVTO_API_KEYS} # en local : $export DEVTO_API_KEYS=ton_api_key
    tag: java
    per-page: 20

# Job de collecte
news:
  fetcher:
    enabled: true
    fixed-delay-ms: 300000   # 5 minutes

# ===============================
# JWT CONFIGURATION (même secret que l'Auth Service)
# ===============================
jwt:
  private-key-path: ${PRIVATE_KEY_PATH:}   # variable d'env Jenkins
  public-key-path: ${PUBLIC_KEY_PATH:}     # variable d'env Jenkins

# Kafka topics
kafka:
  topics:
    tech-news: tech-news-topic

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  db:
    schedule:
      clean-ms: 480000 # 8mn
      limit : 50

logging:
  level:
    com.newstech: DEBUG
    org.springframework.kafka: INFO